#output control
PROCESS_DETAIL=1
SUBTIME_DATAIL=0
FIRSTSUBMIT_DETAIL=0
FILEREAD_LINES=1
COLTYPE=1
FINALNUMSOFSTD=0
SCOREON=0
LONGTAILLOGDETAIL=0
CHECKFORCOL=0
LESSTHANLEASTSUBMITSHOW=0
MAPZEROSHOW=0
#para control
LEASTSUBMIT=8
KMEANSCLUSTER=5
LONGTAIL_ZERO_ADD=0.0001
LONGTAIL_INF_ALT= 10000000
COLLIST=[
"学号",#0
 "题目ID",#1
 "难度",#2
 "首次提交时间",#3
 "最后提交时间",#4
 "投入时间",#5
 "提交次数",#6
 "平均提交间隔",#7
 "通过次数",#8
 "通过率",#9
 "首次AC时间",#10
"首次提交时间和最早提交者的时间差"#11
]
#PROCESS CONTROL
DELETELESSSUBMIT=1